//This file includes all of the files used in this project
//This is done just to keep the main file from being any more cluttered than necessary
#include "allocateArray.c"
#include "processUserInput.c"
#include "getUserInput.c"
#include "deallocateArray.c"
#include "Trie.c"
#include "HashTable.c"
#include "PrintPuzzle.c"
#include "printWordList.c"
#include "loadDictionary.c"
#include "DFS.c"
#include "solveBoggle.c"
#include "generateBoggle.c"
#include "getWordScore.c"
#include "getMaxPossibleScore.c"
#include "startGame.c"
