//This file includes all of the files used in this project
#include "allocateArray.c"
#include "dictionaryStruct.c"
#include "processUserInput.c"
#include "Trie.c"
#include "HashTable.c"
#include "PrintPuzzle.c"
#include "printWordList.c"
#include "addToWordList.c"
#include "isInDictionary.c"
#include "loadDictionary.c"
#include "DFS.c"
#include "solveBoggle.c"
#include "generateBoggle.c"
#include "startGame.c"
